org: sagar

custom:
  secrets: ${file(secrets.json)}
  tableName1: "users"
  tableName2: "surveys"

service: serverless-survey-app
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    AWS_ID: ${self:custom.secrets.AWS_ID}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
      Resource: 
        - "arn:aws:lambda:us-east-1:${self:custom.secrets.AWS_ID}:table/${self:custom.tableName1}"
        - "arn:aws:lambda:us-east-1:${self:custom.secrets.AWS_ID}:table/${self:custom.tableName2}"
functions:
  verify-token:
    handler: functions/authorize.handler

  getSurvey:
      handler: functions/getSurvey.handler
      events:
        - http:
            path: surveys/{id}
            method: get
            cors: true
            authorizer:
              name: verify-token
              identitySource: method.request.header.Authorization
  createSurvey:
    handler: functions/createSurvey.handler
    events:
      - http:
          path: surveys
          method: post
          cors: true
          authorizer:
            name: verify-token
            identitySource: method.request.header.Authorization
  login:
    handler: functions/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  register:
    handler: functions/register.handler
    events:
      - http:
          path: register
          method: post
          cors: true
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName1}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    surveysTable:
            Type: AWS::DynamoDB::Table
            Properties:
              TableName: ${self:custom.tableName2}
              AttributeDefinitions:
                - AttributeName: pk
                  AttributeType: S
                - AttributeName: sk
                  AttributeType: S
              KeySchema:
                - AttributeName: pk
                  KeyType: HASH
                - AttributeName: sk
                  KeyType: RANGE
              ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
